name: tf_streamlit
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - streamlit==1.35.0
      - absl-py==2.1.0
      - alembic==1.13.1
      - altair==5.3.0
      - astunparse==1.6.3
      - attrs==23.2.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - colorlog==6.8.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - flatbuffers==24.3.25
      - fonttools==4.51.0
      - gast==0.4.0
      - gitpython==3.1.43
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - greenlet==3.0.3
      - grpcio==1.64.0
      - gtts==2.5.1
      - h5py==3.11.0
      - idna==3.7
      - jax==0.4.28
      - jaxlib==0.4.28
      - jinja2==3.1.4
      - joblib==1.4.2
      - keras==3.3.3
      - kiwisolver==1.4.5
      - langchain==0.2.3
      - langchain-community==0.2.4
      - langchain-core==0.2.5
      - matplotlib==3.9.0
      - mediapipe==0.10.14
      - ml-dtypes==0.3.2
      - namex==0.0.8
      - numpy==1.23.5
      - oauthlib==3.2.2
      - openai==0.27.4
      - opencv-contrib-python==4.9.0.80
      - opt-einsum==3.3.0
      - optree==0.11.0
      - optuna==3.6.1
      - packaging==23.2
      - pandas==2.2.2
      - pillow==10.3.0
      - playsound==1.3.0
      - protobuf==4.25.3
      - pyarrow==16.1.0
      - pyaudio==0.2.14
      - pydeck==0.9.1
      - pydot==3.0.1
      - pygments==2.18.0
      - python-dotenv==1.0.1
      - pyyaml==6.0.1
      - requests==2.32.1
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rsa==4.9
      - scikeras==0.13.0
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - sounddevice==0.4.6
      - speechrecognition==3.10.4
      - sqlalchemy==2.0.30
      - tensorboard==2.16.2
      - tensorflow==2.16.*
      - tensorflow-estimator==2.12.*
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - toml==0.10.2
      - toolz==0.12.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - typing-extensions==4.11.0
      - urllib3==2.2.1
      - watchdog==4.0.1
      - werkzeug==3.0.3
      - wrapt==1.14.1
      - zipp==3.18.2
